//------------------------------------------------------------------------
// Copyright (c) 2026 Jaxson
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Generated by CMake from the project() VERSION. Change the version there,
// not here.
#include "projectversion.h"

#define stringOriginalFilename	"Glass76.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Glass76 VST3 (64Bit)"
#else
#define stringFileDescription	"Glass76 VST3"
#endif
#define stringCompanyName		"Jaxson\0"
#define stringLegalCopyright	"Copyright (c) 2026 Jaxson"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
